on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  horizon:
    runs-on: ubuntu-latest
    name: horizon

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v2
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        uses: mstksg/get-package@v1
        with:
          apt-get: git python3-pip dfu-util dfu-programmer avrdude
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        working-directory: ./qmk_firmware
        run: |
          mkdir -p keyboards/horizon_tr/keymaps
          ln -s $(pwd)/../horizon_tr keyboards/horizon_tr/keymaps/horizonTR
      - name: Build reviung41 firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb horizon_tr -km horizon_tr
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: reviung41
          path: qmk_firmware/horizon_tr_horizonTR.hex
